apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: go-service
  namespace: imi1-stage
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: go-service
    weight: 100
  wildcardPolicy: None
