apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: imi1-dev-env
  namespace: openshift-gitops
spec:
  destination:
    namespace: imi1-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/imi1-dev/env/overlays
    repoURL: https://github.com/imikiani/gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
